"""users table

Revision ID: 05e87a4ca918
Revises: 34f2334e9939
Create Date: 2019-04-07 12:29:01.667420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e87a4ca918'
down_revision = '34f2334e9939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('givenname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_givenname'), 'user', ['givenname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_givenname'), table_name='user')
    op.drop_column('user', 'givenname')
    # ### end Alembic commands ###
